---
- name: Install Python packages from the command line
  hosts: all
  become: yes  # Run tasks with root privileges (sudo)

  tasks:
    - name: Ensure python3-pip is installed (for Debian/Ubuntu systems)
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install specified Python packages
      ansible.builtin.pip:
        name: "{{ packages.split(',') }}" # Splits the string into a list for pip
        state: present
        extra_args: --break-system-packages
      when: packages is defined and packages != "" # Safety check to run only if packages are provided
